diff --git a/wrangler.toml b/wrangler.toml
new file mode 100644
index 0000000000000000000000000000000000000000..78b61133ce98bd1f49543ca4a202cf85e25f3ac9
--- /dev/null
+++ b/wrangler.toml
@@ -0,0 +1,6 @@
+name = "ghostaiv1"
+main = "worker-ghostaiv1/index.js"
+compatibility_date = "2024-10-16"
+
+[vars]
+# Add your bindings like OPENAI_API_KEY in Cloudflare dashboard or via `wrangler secret put`.
